project:
  type: website
  output-dir: docs

website:
  title: "Bilikisu Wunmi Olatunji"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blogs.qmd
      - projects.qmd
      - contactme.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

