project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true
  
website:
  title: "Bilikisu Wunmi Olatunji"
  navbar:
    pinned: true
    logo: /img/logo.png
    
    right:
      - text: Blogs
        href: blogs.qmd
      - text: Projects
        href: projects.qmd
      - icon: twitter
        href: https://twitter.com/qbwoa
      - icon: linkedin
        href: https://www.linkedin.com/in/bilikisuolatunji/
      - icon: github
        href: https://github.com/BWOlatunji/

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    center: |
      <span class="faux-block">&#169; 2023 Bilikisu Wunmi Olatunji CC BY-SA 4.0</span>
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


