baseURL: /
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Bilikisu Wunmi Olatunji - Data Scientist, Agile Coach
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
    - name: Blog
      url: blog
      weight: 6
  sitemap:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: blog
      weight: 2
params:
  blogPageURL: blog
  contactButtonLabel: Work with Bilikisu
  contactLink: '#contact'
  copyright: All right reserved copyright © Bilikisu Wunmi Olatunji 2022-2023
  footerLogo: images/site-navigation/BWO.png
  formspreeURL: https://formspree.io/f/xaykzpna
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/BWO.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/bilikisuolatunji/
      weight: 1
    - icon: fa-youtube-square
      url: https://www.youtube.com/channel/UC9T4FraKNaqJ05LT6WRRIOQ/
      weight: 2
    - icon: fa-twitter-square
      url: https://twitter.com/qbwoa/
      weight: 3
